@startuml Sequence Diagram
actor Player
participant GameController
participant BoardGame
participant Dice
participant Die
participant Tile
participant TileAction


Player -> GameController: throws dice
GameController -> BoardGame: boardGame.moveplayer(player)
BoardGame -> Dice: dice.rollDice()
Dice -> Die: die.roll()
Dice -> Die: die.roll()
Dice <- Die: random(1 - 6)
Dice <- Die: random(1 - 6)
BoardGame <- Dice: random(1 - 12)
BoardGame -> Tile: getBoardTile(playerTile).hasAction()
BoardGame <- Tile: getBoardTile(playerTile).!hasAction()
Tile -> TileAction: tileActionResult()
Tile <- TileAction: LadderAction().tileActionResult()
Tile <- TileAction: SnakeAction().tileActionResult()
BoardGame <- Tile: int endTile.tileId
GameController <- BoardGame: player moved
Player <- GameController: player moved
@enduml