@startuml Sequence Diagram
actor Player
participant GameController
participant BoardGame
participant Dice
participant Die
participant Tile
participant TileAction


Player -> GameController: throws dice
GameController -> BoardGame: throw dice
BoardGame -> Dice: rollDice()
Dice -> Die: getDie()
Dice <- Die: result()
BoardGame <- Dice: diceResult()
BoardGame -> Tile: movePlayer()
Tile -> TileAction: getAction()
Tile <- TileAction: LadderAction()
Tile <- TileAction: SnakeAction()
BoardGame <- Tile: movePlayer()
GameController <- BoardGame: player moved
Player <- GameController: player moved
@enduml