@startuml Sequence Diagram
actor Player
participant GameController
participant Dice
participant Die
participant BoardGame
participant Board
participant Tile
participant TileAction


Player -> GameController: throwDice()
GameController -> Dice: throw()
Dice -> Die: getDie()
Dice <- Die: result()
GameController <- Dice: amountToMove()
GameController -> BoardGame: movePlayer()
BoardGame -> Board: getNextTile()
Board -> Tile: getTileAction()
Tile -> TileAction: getAction()
Tile <- TileAction: LadderAction()
Board <- Tile: LadderAction()
BoardGame <- Board: tileResult()
GameController <- BoardGame: movePlayerTo()
Player <- GameController: MovePlayerToTile()
@enduml